name: Sync Dataset from Google Drive

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # allow manmanual trigger

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Download latest dataset
        run: |
          rclone sync gdrive:5003-BigData/data/ ./data/ --progress --update
